# Data I/O: .rds files in data/{2_processed,3_done,temp,1_raw} with the same
# basenames the Stata pipeline uses for its .dta files. Paths are relative to code/.

proc_path <- function(name) file.path("../data/2_processed", paste0(name, ".rds"))
done_path <- function(name) file.path("../data/3_done", paste0(name, ".rds"))
temp_path <- function(name) file.path("../data/temp", paste0(name, ".rds"))
raw_path  <- function(name) file.path("../data/1_raw", paste0(name, ".rds"))

# compress = FALSE: the pipeline writes ~10k small files; compression dominates runtime
write_proc <- function(df, name) saveRDS(as.data.frame(df), proc_path(name), compress = FALSE)
write_done <- function(df, name) saveRDS(as.data.frame(df), done_path(name), compress = FALSE)
write_temp <- function(df, name) saveRDS(as.data.frame(df), temp_path(name), compress = FALSE)
write_raw  <- function(df, name) saveRDS(as.data.frame(df), raw_path(name),  compress = FALSE)

read_proc <- function(name) as_tibble(readRDS(proc_path(name)))
read_done <- function(name) as_tibble(readRDS(done_path(name)))
read_temp <- function(name) as_tibble(readRDS(temp_path(name)))
read_raw  <- function(name) {
  # raw inputs may be original .dta (shipped) or .rds (generated by this pipeline)
  rds <- raw_path(name)
  if (file.exists(rds)) return(as_tibble(readRDS(rds)))
  haven::zap_formats(haven::zap_labels(haven::read_dta(file.path("../data/1_raw", paste0(name, ".dta")))))
}

# Stata `merge 1:1 date using ...` semantics: all master rows keep master values
# (including conflicting columns); using-only rows are appended with using values.
stata_merge_11 <- function(master, using, by = "date") {
  new_cols <- setdiff(names(using), names(master))
  matched <- dplyr::left_join(master, using[c(by, new_cols)], by = by)
  u_only <- dplyr::anti_join(using, master, by = by)
  dplyr::bind_rows(matched, u_only) |> dplyr::arrange(across(all_of(by)))
}

ensure_dirs <- function() {
  for (d in c("../figures", "../data/2_processed", "../data/3_done", "../data/temp",
              "../output", "../output/4", "../output/5", "../output/prediction",
              "../output/HeatMaps", "../output/HeatMaps/4", "../output/HeatMaps/5",
              "../output/HeatMaps/Prediction",
              "./figures", "./figures/Aggregate", "./figures/Prediction",
              "./figures/Replication", "./figures/Robustness", "./matlab")) {
    if (!dir.exists(d)) dir.create(d, recursive = TRUE)
  }
}
